name: Extract VTT Text
on:
  push:
    branches:
      - main  # Adjust the branch name as needed
      jobs:
  extract-vtt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install axios

    - name: Extract VTT Text
      id: extract
      run: |
        const axios = require('axios');
        const fs = require('fs');

        const vttDownloadLink = 'https://us06web.zoom.us/rec/download/4WMDtpB2OQmASgO3xbTOKE_eAPFiXQW8ZB3qOsPFX4zzmLV5TzV6vBggKZcrAuw-mRKE6N_bnAYVBLmd.gA38x-keLzUcTJ5o';

        axios.get(vttDownloadLink)
          .then(response => {
            const vttContent = response.data;
            const extractedText = extractTextFromVtt(vttContent);

            // Store the extracted text in a file (optional)
            fs.writeFileSync('extracted_text.txt', extractedText);

            // Output the extracted text
            console.log(extractedText);
          })
          .catch(error => {
            console.error('Failed to download VTT file:', error);
          });

        function extractTextFromVtt(vttContent) {
          // Implement your text extraction logic here
        }
